#!/bin/bash
echo -e "======= SHARDCORE RUN $(date) ======="

# cd into this script location (should be shardcore dir)
cd $(dirname $0)

# launch shardcore
java -jar dist/shardcore-latest.jar |& tee logs/teelog.txt
